version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend_dockerfile  # Custom Dockerfile for frontend
    ports:
      - "3000:80"

  backend:
    build:
      context: ./backend
      dockerfile: backend_dockerfile  # Custom Dockerfile for backend
    ports:
      - "5000:5000"
    environment:
      - API_KEY=${API_KEY}
